# Generated by Django 6.0.5 on 2026-05-14 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_coches/')),
                ('coches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='coches.coche')),
            ],
        ),
    ]
